services:
  backend:
    build:
      context: ./backend
    container_name: proxmox-dashboard-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    env_file: ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: proxmox-dashboard-frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8081}:80"
